---
- hosts: all
  become: yes
  tasks:
    - name: Install basic packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - git  # Add any other packages you need

    - name: Install Docker using the convenience script
      command: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      args:
        creates: /usr/bin/docker  # Only run if Docker is not already installed

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose
      command: >
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_os_family | lower }}-{{ ansible_architecture | lower }}" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Set permissions for Docker Compose
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add existing user to group docker
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes


#ansible-playbook -i inventory.ini deploy.yml

#τωρα τα σηκωνω manually αλλα μπορω να προσθέσω:
#  - name: Copy docker-compose.yaml to target machine
#      copy:
#        src: /home/it2021154/Desktop/DraftJobSystem/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis./docker-compose.yml
#        dest: /home/it2021154/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis/docker-compose.yml
#
#    - name: Start services with Docker Compose
#      command: docker-compose up -d
#      args:
#        chdir: /home/it2021154/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis
