version: '3.8'  # Ensure you use a version that suits your needs

services:
  db:
    image: postgres:14
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: screeningdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - dslabdb:/var/lib/postgresql/data/

  spring:
    image: sp  # Change this to your specific image if needed
    build:
      context: .
      dockerfile: nonroot.Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/screeningdb
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: pass123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - dslabdb:/app/data  # Assuming you want to mount a volume here, adjust path as necessary

  frontend:
    build:
      context: ./frontend/vue3-project-screening  # Adjust this path as needed
      dockerfile: Dockerfile  # Specify Dockerfile name if needed
    ports:
      - "8080:80" #now frontend listens in localhost:8080
    depends_on:
      spring:
        condition: service_healthy

volumes:
  dslabdb:  # Define the named volume here




  # It worked until now backend, db, frontend
  # (Also in order to use the port 5432 for db I need first If I run locally the project to sudo systemctl stop postgresql)
  # Issues pending to fix: minio, parsing tika that cannot be find in maven repository - now I need to comment tika dependency and relevant classes
  # assessible in frontend through: http://localhost:8080
  #
  #docker-compose up --build
  #
  #
  #
  #
  #
  #
  #
  #if it does not find the dbuser for db in docker:
  # I can connect to the database: docker exec -it application-submission-and-pre-screening-system-based-on-resume-analysis-db-1 psql -U dbuser -d screeningdb
  #
  #useful commands if I am inside postgresql command line
  #\du          -- List roles
  #\l           -- List databases
  #CREATE USER dbuser WITH PASSWORD 'pass123';
  #CREATE DATABASE screeningdb;
  #GRANT ALL PRIVILEGES ON DATABASE screeningdb TO dbuser;
