all:
  hosts:
    vagrant:
      ansible_host: 192.168.56.3
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key

#firstly I will use vagrant up and then ansible-playbook -i hosts.yml deploy.yml to run my playbook
#then I can test it in the port that I have added in my file (http://localhost:8081 for frontend and http://localhost:9091 for backend)


