pipeline {
    agent any
    environment {
        BACKEND_IMAGE = 'ghcr.io/panos994/application-submission-and-pre-screening-system-based-on-resume-analysis/backend:1.0'
        FRONTEND_IMAGE = 'ghcr.io/panos994/application-submission-and-pre-screening-system-based-on-resume-frontend:latest'
    }
    stages {
        stage('Docker Login to GHCR') {
            steps {
                script {
                    def github_username = "Panos994"
                    def github_token = "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"
                    // Log in to GHCR using the token and username
                    sh "echo ${github_token} | docker login ghcr.io -u ${github_username} --password-stdin"
                }
            }
        }
        stage('Pull Backend Image') {
            steps {
                sh 'docker pull $BACKEND_IMAGE'
            }
        }
        stage('Pull Frontend Image') {
            steps {
                sh 'docker pull $FRONTEND_IMAGE'
            }
        }
        stage('Deploy to Kubernetes') {
            environment {
                KUBECONFIG = '/etc/rancher/k3s/k3s.yaml' // Path to kubeconfig file on EC2 instance
            }
            steps {
                // Applying database and MinIO manifests using relative paths from the repository
                sh 'kubectl apply -f k3s/database/deployment.yaml'
                sh 'kubectl apply -f k3s/database/service.yaml'
                sh 'kubectl apply -f k3s/minio'

                // Apply the backend and frontend images from GitHub Packages
                sh 'kubectl apply -f k3s/backend/deployment.yaml'  // Path to backend deployment.yaml
                sh 'kubectl apply -f k3s/backend/service.yaml'     // Path to backend service.yaml

                // Ensure backend deployment exists, or create it if it doesn't
                script {
                    def backendDeploymentExists = sh(script: "kubectl get deployment spring-backend -o name", returnStatus: true) == 0
                    if (!backendDeploymentExists) {
                        echo "Backend deployment not found, creating it."
                        // Create the backend deployment if it doesn't exist
                        sh 'kubectl apply -f k3s/backend/deployment.yaml'  // Applying backend deployment if it doesn't exist
                    }
                }

                // Set the images for the backend and frontend deployments
                sh 'kubectl set image deployment/spring-backend spring-backend=$BACKEND_IMAGE'
                sh 'kubectl set image deployment/vue-frontend vue-frontend=$FRONTEND_IMAGE'
            }
        }
    }
}



