pipeline {
    agent any
    environment {
        DOCKER_REGISTRY = 'YOUR_DOCKER_REGISTRY' // replace with your Docker registry
    }
    stages {
        stage('Build and Push Backend Image') {
            steps {
                dir('/home/it2021154/Desktop/DraftJobSystem/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis') {
                    sh 'docker build -t $DOCKER_REGISTRY/sp:latest -f backend/Dockerfile .'
                    sh 'docker push $DOCKER_REGISTRY/sp:latest'
                }
            }
        }
        stage('Build and Push Frontend Image') {
            steps {
                dir('/home/it2021154/Desktop/DraftJobSystem/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis/frontend/vue3-project-screening') {
                    sh 'docker build -t $DOCKER_REGISTRY/vue-frontend:latest -f Dockerfile .'
                    sh 'docker push $DOCKER_REGISTRY/vue-frontend:latest'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                // Applying database and MinIO manifests
                sh 'kubectl apply -f /home/it2021154/Desktop/DraftJobSystem/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis/k3s/database'
                sh 'kubectl apply -f /home/it2021154/Desktop/DraftJobSystem/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis/k3s/minio'
                // Applying backend and frontend manifests
                sh 'kubectl apply -f /home/it2021154/Desktop/DraftJobSystem/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis/k3s/backend'
                sh 'kubectl apply -f /home/it2021154/Desktop/DraftJobSystem/Application-Submission-and-Pre-Screening-System-Based-on-Resume-Analysis/k3s/frontend'
            }
        }
    }
}
