apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTXpFME16RXpNamd3SGhjTk1qUXhNVEV5TVRjd09EUTRXaGNOTXpReE1URXdNVGN3T0RRNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTXpFME16RXpNamd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRSW1mMFF3VVNBZHZSOWh1WktmMXB3SHdxbDdFNXNLVlI2a3NpQkRKaSsKWmJISERtY2hPNUh2amZ4MEgwNThUemxxWHF2Uzh3bjZNU3RnTHVldWpxcnZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWV2RlhqV2VXb0U1NmJYaG5pOFBXClVOU2prOU13Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnYnU5SEtIMmdZWTdMTm8rT3RoQTBWT3VQRXJYaVAxanAKSHl4cysvd0EwemtDSVFDNWYvWjhpbmxXdGFKV3RaRHl1N1ZTSkEzT1NGWkliVDZVWjhzOWMwUlNVUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://13.60.61.42:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJSGh0eXU3N0lUd293Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOek14TkRNeE16STRNQjRYRFRJME1URXhNakUzTURnME9Gb1hEVEkxTVRFeApNakUzTURnME9Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJOS3p0bTRqQ1NkQlJjSWwKRWI3d3pIOHduTTNsUGpYRUloV3kxSlM3OGZ2cE95V1JLbE82OUdpNjZWZlUrQVgxY0duR2l2dHVTZlBZNy9jawprQm9hclZ5alNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCU2RVdU5JL3VNWFJDZENWaVk1NEJja2JQdHlXakFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCaklvYmRNTDJoZUo0eFRYa0JWS0NmQzN3a0V5bjlPUFdTOUdESUdWdGNld0lnR1JSSkExZVVDSHZFaUdlUApON2loZFN4ZXZtUityTExmamdzMzVUcG5rcnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTXpFME16RXpNamd3SGhjTk1qUXhNVEV5TVRjd09EUTRXaGNOTXpReE1URXdNVGN3T0RRNApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTXpFME16RXpNamd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUU1hVYitGRnZGTFVOZS9KVW5iWENvbUU3dG1Ld25ZR2FsSG1tR2VjcnoKN1hOekw5Q0hqTXlsT24zTEcwQk9Zd1VaSEViZWh1RERjTUNWVkYrWTFSVFFvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW5WTGpTUDdqRjBRblFsWW1PZUFYCkpHejdjbG93Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQVBFSFkzcHpiRHpXQUJ0bkZqanFVL3BYMzAwcDVEclQKamZVTzZEQitXQjdIQWlFQTg4OXBBek1ORTdWbmd4VTB2WW9hU3lJR1ZVVUpVU2lCWENRYTB2V0NFNjA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU55UXpMVnRnSWRjV3MweU5mRGVtVU1XMGdhOGQ0NUFKQ0wzTUZSbnZndmxvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMHJPMmJpTUpKMEZGd2lVUnZ2RE1mekNjemVVK05jUWlGYkxVbEx2eCsrazdKWkVxVTdyMAphTHJwVjlUNEJmVndhY2FLKzI1Sjg5anY5eVNRR2hxdFhBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=







#oso afora to Jenkisfile moy
#Primary Focus: This Jenkinsfile is designed for deploying pre-built Docker images to a Kubernetes (K3s) cluster. It doesn't deal with the build or push steps for Docker images (like Jenkinsfile 2 does) but assumes that the images are already built and available in a container registry (in this case, GitHub Container Registry).

#my Jenkinsfile is focused on containerized deployments using Kubernetes, leveraging Docker images pulled from a container registry.