apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: http-port
      port: 9000
      targetPort: 9000
    - name: console-port
      port: 9001
      targetPort: 9001
  selector:
    app: minio
  type: ClusterIP
