apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Paste the contents of your default.conf file here
    server {
      listen 80;  # Listen on port 80
      server_name localhost;  # Change this if you have a specific domain - I have tried AWS IP: 13.49.230.239

      location / { #
        proxy_pass http://spring:9090;  # Change <your_spring_boot_app> to the actual service name or IP (the name in docker-compose.yaml is spring so it should be spring:9090)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      error_page 404 /404.html;
      error_page 500 /500.html;
    }
